[package]
name = "rclip"
version = "0.1.0"
authors = ["UnkwUsr <ktoto2707043@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"

[dependencies.xcb]
version = "0.9.0"
features = ["xfixes"]

